name: smartfarm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.1.0-11.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.62.0
  http: ^0.13.5
  flutter_provider: ^2.1.0
  provider: ^6.0.5
  image: ^4.0.16
  shared_preferences: ^2.1.0
  webview_flutter: ^4.2.0
  path_provider: ^2.0.14
  get: ^4.6.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
